spring:
  application:
    name: ticket-service-client
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.1.7:8761/eureka}
  instance:
    preferIpAddress: true