spring:
  application:
    name: user-service-client
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-service:8761/eureka}
  instance:
    preferIpAddress: true