spring:
  application:
    name: api-gateway-service
server:
  port: 8084
  servlet:
    contextPath: /api/gateway
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-service:8761/eureka}
    fetchRegistry: true
  instance:
    preferIpAddress: true

logging:
  level:
    com.micro.services.api.gateway.service.client.ticketservice.TicketServiceHealthCheckClient: debug
    com.micro.services.api.gateway.service.client.userservice.UserServiceHealthCheckClient: debug