spring:
  application:
    name: api-gateway-service
server:
  port: 8084
  servlet:
    contextPath: /api/gateway
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.1.7:8761/eureka}
    fetchRegistry: true
  instance:
    preferIpAddress: true
logging:
  level:
    com.demo.service.client.WeatherServiceHealthCheckClient: DEBUG